#!/usr/bin/env bash

# Builtins-Base
alias cd="pushd"
alias p="popd"
alias cp="cp -i"     # overwrite confirmation
alias mv="mv -i"     # overwrite confirmation
alias df="df -h"     # human-readable sizes
alias du="du -h"     # human-readable sizes
alias free="free -h" # human-readable sizes
alias ll="ls -l"     # detailed file list
alias la="ls -lA"    # detailed file list with hidden files
alias wh="which -aS" # Informative version of which
alias less='less --RAW-CONTROL-CHARS'
alias sudo='sudo '   # Carry over environment & forces sudo to use aliases
alias vim="nvim"     # Force nvim usage
alias oldvim="\vim"  # Use dealiased vim

# Generic
alias ls="LC_COLLATE=C ls --group-directories-first --color=always --classify -h"

## docker-compose
alias dc="docker-compose"
alias dcup="docker-compose up -d"
alias dcdown="docker-compose down"
alias dclog="docker-compose logs -f"

## git
alias gresign="git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD" # git resign all commits from history
alias g="git status"

alias gc="git commit"
alias gca="git commit --amend"

alias gr="git rebase"
alias gri="git rebase -i"
alias grc="git rebase --continue"

alias glo='git log --pretty=format:"%h - %an, %ar : %s" | grep "Aakash Hemadri"'
