#!/usr/bin/env bash
#
# Environment variables for debian/cli
#

export SYSTEMD_EDITOR="vim"
#export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

export LANG="en_IN.UTF-8"
export EDITOR="nvim"
export PAGER="most"

# Specify vimrc path
#shellcheck disable=SC2016
export VIMCONFIG="$XDG_CONFIG_HOME/vim"
export VIMINIT='let $MYVIMRC="$VIMCONFIG/config.vim" | source $MYVIMRC'

# Specify nvm path & initiate nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
