#!/usr/bin/env bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo -e "$YEL*** Installing $PUR${DIR#$DOTS_SOURCE/}/$(basename $0 .install)$RST"

rm -f "$HOME/.vimrc" \
    "$HOME/.viminfo"

PLUG_SOURCE="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

if [[ ! -e $XDG_CONFIG_HOME/vim/autoload/plug.vim ]]; then
    curl --create-dirs -sSfLo $XDG_CONFIG_HOME/vim/autoload/plug.vim "$PLUG_SOURCE"
fi
